
export const  TEST_USERS_PARAM = "TEST_USERS_PARAM";
export const  SEND_USERS_AUTHORIZATION = "SEND_USERS_AUTHORIZATION";
export const  USERS_ERROR_AUTHORIZATION = "USERS_ERROR_AUTHORIZATION";
export const  TEST_USERS_STATUS = "TEST_USERS_STATUS";
